baseURL = "https://rakhmatwh.github.io/"
#baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Cathetanku'
theme = "PaperMod"

[params.profileMode]
  enabled = true
  title = "Halo, Saya Rakhmat"
  subtitle = "Selamat datang di blog catatan saya"
  imageUrl = "me.png"
  imageWidth = 260
  imageHeight = 220
  
[[params.profileMode.buttons]]
    name = "Baca Tulisan Saya"
    url = "posts"

# --- Pengaturan Output untuk Search (Wajib untuk PaperMod) ---
[outputs]
    home = ["HTML", "RSS", "JSON"]

# --- Pengaturan Menu Navigasi ---
[[menu.main]]
    identifier = "archives"
    name = "Arsip"
    url = "/archives/"
    weight = 10

[[menu.main]]
    identifier = "search"
    name = "Cari"
    url = "/search/"
    weight = 20